[build]
builder = "nixpacks"

[[services]]
name = "backend"
source = "backend"
startCommand = "python run.py"

[[services]]
name = "scheduler"
source = "backend"
startCommand = "python scheduler.py"

[[services]]
name = "worker"
source = "backend"
startCommand = "python worker.py"
