/**
 * Post-build prerender script — renders SPA pages to static HTML.
 * Runs after `vite build`.
 *
 * Reads routes from public/routes.json (generated by generate-sitemap.cjs),
 * uses Puppeteer to render each page, saves HTML to dist/__prerendered__/.
 *
 * Usage: node scripts/prerender.mjs
 *   --serve-dir  Path to dist directory (default: dist)
 *   --routes     Path to routes JSON (default: public/routes.json)
 *   --concurrency Number of parallel pages (default: 3)
 *   --timeout    Page load timeout ms (default: 15000)
 *   --strict     Fail build if any page fails to render
 */

import { createServer } from "http";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DIST = path.resolve(ROOT, "dist");
const PUBLIC = path.resolve(ROOT, "public");
const ROUTES_FILE = path.resolve(PUBLIC, "routes.json");
const OUTPUT_DIR = path.resolve(DIST, "__prerendered__");

// ── Configuration ──
const PORT = 4173;
const CONCURRENCY = 3;
const TIMEOUT = 15000;
const STRICT = false;

const ARTICLES_DIR = path.resolve(ROOT, "..", "backend", "app", "data", "articles");

// ── Content selectors to wait for (route prefix → CSS selector) ──
const WAIT_FOR = [
  { prefix: "/articles/", selector: ".article-content" },
  { prefix: "/compatibility/elements/", selector: ".landing-hero" },
  { prefix: "/articles", selector: ".article-grid" },
  { prefix: "/", selector: ".bond-hero" },
];

function getWaitSelector(route) {
  for (const w of WAIT_FOR) {
    if (route.startsWith(w.prefix)) return w.selector;
  }
  return null;
}

// ── Static file + API mock server ──
function createPreviewServer() {
  const MIME = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".xml": "application/xml",
  };

  return createServer((req, res) => {
    const url = new URL(req.url, `http://localhost:${PORT}`);

    // ── API mock: articles list ──
    if (url.pathname === "/api/content/articles") {
      const metadataPath = path.join(ARTICLES_DIR, "metadata.json");
      if (existsSync(metadataPath)) {
        const data = readFileSync(metadataPath, "utf-8");
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ success: true, articles: JSON.parse(data) }));
        return;
      }
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ success: true, articles: [] }));
      return;
    }

    // ── API mock: single article ──
    const articleMatch = url.pathname.match(/^\/api\/content\/articles\/(.+)$/);
    if (articleMatch) {
      const slug = articleMatch[1];
      const articlePath = path.join(ARTICLES_DIR, `${slug}.json`);
      if (existsSync(articlePath)) {
        const data = readFileSync(articlePath, "utf-8");
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ success: true, article: JSON.parse(data) }));
        return;
      }
      res.writeHead(404, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ success: false, error: "Article not found" }));
      return;
    }

    // ── Static file serving ──
    let filePath = path.join(DIST, url.pathname === "/" ? "index.html" : url.pathname);

    if (!existsSync(filePath)) {
      // Try adding .html extension (for clean URLs)
      const htmlPath = filePath + ".html";
      if (existsSync(htmlPath)) {
        filePath = htmlPath;
      } else {
        // Fallback to index.html for SPA routing
        filePath = path.join(DIST, "index.html");
      }
    }

    const ext = path.extname(filePath).toLowerCase();
    const contentType = MIME[ext] || "application/octet-stream";

    try {
      const content = readFileSync(filePath);
      res.writeHead(200, { "Content-Type": contentType });
      res.end(content);
    } catch {
      // Final fallback
      try {
        const fallback = readFileSync(path.join(DIST, "index.html"));
        res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
        res.end(fallback);
      } catch {
        res.writeHead(500);
        res.end("Server error");
      }
    }
  });
}

// ── Main prerender function ──
async function prerender() {
  console.log("[prerender] Starting...");

  // Read routes
  if (!existsSync(ROUTES_FILE)) {
    console.warn(`[prerender] WARNING: ${ROUTES_FILE} not found. Run sitemap generation first.`);
    console.warn("[prerender] Using default routes (homepage only).");
    writePrerenderedFile("/", "<html><body><p>Prerender placeholder</p></body></html>");
    return;
  }

  const routes = JSON.parse(readFileSync(ROUTES_FILE, "utf-8"));
  console.log(`[prerender] Routes to render: ${routes.length}`);

  // Ensure output directory
  mkdirSync(OUTPUT_DIR, { recursive: true });

  // Start preview server
  const server = createPreviewServer();
  await new Promise((resolve) => server.listen(PORT, "127.0.0.1", resolve));
  console.log(`[prerender] Preview server at http://127.0.0.1:${PORT}`);

  // Try to load Puppeteer
  let browser;
  try {
    const puppeteer = await import("puppeteer");
    browser = await puppeteer.default.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
    });
  } catch (e) {
    console.warn(`[prerender] Puppeteer not available (${e.message})`);
    console.warn("[prerender] Skipping prerender — SPA fallback will serve pages.");
    server.close();
    return;
  }

  // Process routes in parallel with concurrency limit
  let successCount = 0;
  let failCount = 0;
  let currentIndex = 0;

  async function processRoute() {
    while (currentIndex < routes.length) {
      const idx = currentIndex++;
      const route = routes[idx];

      let page;
      try {
        page = await browser.newPage();
        page.setDefaultTimeout(TIMEOUT);

        const url = `http://127.0.0.1:${PORT}${route}`;
        console.log(`[prerender] [${idx + 1}/${routes.length}] ${route}`);

        await page.goto(url, { waitUntil: "networkidle0", timeout: TIMEOUT });

        // Wait for content-specific selector
        const selector = getWaitSelector(route);
        if (selector) {
          try {
            await page.waitForSelector(selector, { timeout: 8000 });
          } catch {
            console.warn(`[prerender] WARNING: Selector "${selector}" not found for ${route}`);
          }
        }

        const html = await page.content();
        writePrerenderedFile(route, html);

        successCount++;
      } catch (err) {
        failCount++;
        console.error(`[prerender] FAILED [${idx + 1}/${routes.length}] ${route}: ${err.message}`);
      } finally {
        if (page) await page.close();
      }
    }
  }

  const workers = Array.from({ length: Math.min(CONCURRENCY, routes.length) }, () => processRoute());
  await Promise.all(workers);

  await browser.close();
  server.close();

  console.log(`\n[prerender] Done. ${successCount} rendered, ${failCount} failed.`);

  if (failCount > 0 && STRICT) {
    process.exit(1);
  }
}

function writePrerenderedFile(route, html) {
  // Convert route to file path
  let filePath;
  if (route === "/") {
    filePath = path.join(OUTPUT_DIR, "index.html");
  } else if (route.endsWith("/")) {
    filePath = path.join(OUTPUT_DIR, route.slice(1), "index.html");
  } else {
    filePath = path.join(OUTPUT_DIR, route.slice(1) + ".html");
  }

  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, html, "utf-8");
}

prerender().catch((err) => {
  console.error("[prerender] Fatal error:", err);
  process.exit(1);
});
