/**
 * Post-build prerender script — renders SPA pages to static HTML.
 * Runs after `vite build`.
 *
 * Reads routes from public/routes.json (generated by generate-sitemap.cjs),
 * uses Puppeteer to render each page, saves HTML to dist/__prerendered__/.
 *
 * Usage: node scripts/prerender.mjs
 *   --serve-dir  Path to dist directory (default: dist)
 *   --routes     Path to routes JSON (default: public/routes.json)
 *   --concurrency Number of parallel pages (default: 3)
 *   --timeout    Page load timeout ms (default: 15000)
 *   --strict     Fail build if any page fails to render
 */

import { createServer } from "http";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PUBLIC = path.resolve(ROOT, "public");

function readArgument(name, fallback) {
  const index = process.argv.indexOf(name);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
}

const DIST = path.resolve(ROOT, readArgument("--serve-dir", "dist"));
const ROUTES_FILE = path.resolve(ROOT, readArgument("--routes", "public/routes.json"));
const OUTPUT_DIR = path.resolve(DIST, "__prerendered__");

// ── Configuration ──
const PORT = 4173;
const CONCURRENCY = Number(readArgument("--concurrency", "3"));
const TIMEOUT = Number(readArgument("--timeout", "15000"));
const HYDRATION_VIEWPORT = {
  width: Number(readArgument("--viewport-width", "1280")),
  height: Number(readArgument("--viewport-height", "900")),
  deviceScaleFactor: 1,
};
const STRICT = process.argv.includes("--strict");

const ARTICLES_DIR = path.resolve(ROOT, "..", "backend", "app", "data", "articles");

// ── Content selectors to wait for (route prefix → CSS selector) ──
const WAIT_FOR = [
  { prefix: "/relationship-patterns/", selector: '[data-prerender-ready="relationship-pattern-article"]' },
  { prefix: "/methodology", selector: '[data-prerender-ready="methodology"]' },
  { prefix: "/compare/", selector: ".comparison-table" },
  { prefix: "/faq", selector: ".content-page" },
  { prefix: "/compatibility", selector: ".compact-page" },
  { prefix: "/articles/", selector: ".article-content" },
  { prefix: "/compatibility/elements/", selector: ".landing-hero" },
  { prefix: "/elements/", selector: ".element-personality-hero" },
  { prefix: "/articles", selector: ".article-grid" },
  { prefix: "/", selector: ".bond-hero" },
];

const FAQ_ENTRIES = [
  ["What is a BaZi / five-element compatibility test?", "A BaZi compatibility test compares patterns derived from two birth records using concepts from the Chinese Five Elements and Four Pillars traditions. Elemental Bond first provides a simplified element-level preview; a full traditional chart would also consider year, month, day, hour, and their interactions."],
  ["How is this different from Western astrology compatibility?", "Western astrology commonly compares planetary placements and zodiac signs. BaZi uses a Chinese calendrical framework organized around heavenly stems, earthly branches, yin-yang, and the Five Elements. The systems use different inputs and interpretive rules, so their results are not directly interchangeable."],
  ["Do I need my exact birth time?", "No. The free core-element and relationship previews can run from birth dates alone. An exact birth time supplies the hour pillar in a full BaZi chart, so time-dependent interpretations are necessarily less specific when the hour is unknown."],
  ["Is this based on real Chinese astrology methodology?", "The product vocabulary and relationship framework draw from BaZi and Five Elements traditions. The instant free result is deliberately simplified and should not be represented as a complete professional Four Pillars calculation. It is an interpretive reflection tool, not a scientifically validated assessment."],
  ["How accurate is elemental.bond compared to Co-Star or The Pattern?", "There is no independent accuracy dataset that supports a numerical comparison among these products. Co-Star is associated with Western astrology, The Pattern presents astrology-based personality and timing content, and Elemental Bond uses a BaZi-inspired Five Elements framework. Their outputs should be compared by method and scope, not by an unsupported accuracy score."],
];

const STATIC_META = {
  "/": {
    title: "Five-Element Personality Test — Free BaZi-Inspired Reading",
    description: "What does your birth date suggest about your relationship patterns? Get a free five-element personality reading without creating an account.",
    schema: {
      "@context": "https://schema.org",
      "@type": "WebApplication",
      name: "Elemental Bond Five-Element Personality Test",
      applicationCategory: "LifestyleApplication",
      operatingSystem: "Web",
      url: "https://elemental.bond/",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    },
  },
  "/compatibility": {
    title: "BaZi Compatibility Test — Free Five-Element Relationship Preview",
    description: "Enter another birth date to see a free five-element relationship dynamic, then choose whether to unlock the full report.",
    schema: {
      "@context": "https://schema.org",
      "@type": "Product",
      name: "Decode This Connection",
      description: "A Personal Five-Element Relationship Reading.",
      brand: { "@type": "Brand", name: "Elemental Bond" },
      offers: {
        "@type": "Offer",
        price: "14.90",
        priceCurrency: "USD",
        availability: "https://schema.org/InStock",
        url: "https://samzhu168.gumroad.com/l/decode-this-connection",
      },
    },
  },
  "/faq": {
    title: "What Is BaZi Compatibility? — Five-Element Test FAQ",
    description: "What is BaZi compatibility, is birth time required, and how does a five-element test differ from Western astrology apps? Direct, factual answers.",
    schema: {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: FAQ_ENTRIES.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })),
    },
  },
  "/compare/co-star-vs-elemental-bond": {
    title: "Co-Star vs Elemental Bond — Method, Free Access, and Price",
    description: "A neutral comparison of Co-Star and Elemental Bond by method, free access, subscription status, and disclosed price.",
    schema: { "@context": "https://schema.org", "@type": "WebPage", name: "Co-Star vs Elemental Bond", about: ["Co-Star", "Elemental Bond", "astrology compatibility"] },
  },
  "/compare/the-pattern-vs-elemental-bond": {
    title: "The Pattern vs Elemental Bond — Method, Free Access, and Price",
    description: "A neutral comparison of The Pattern and Elemental Bond by method, free access, subscription status, and disclosed price.",
    schema: { "@context": "https://schema.org", "@type": "WebPage", name: "The Pattern vs Elemental Bond", about: ["The Pattern", "Elemental Bond", "relationship compatibility"] },
  },
};

function getWaitSelector(route) {
  for (const w of WAIT_FOR) {
    if (route.startsWith(w.prefix)) return w.selector;
  }
  return null;
}

// ── Static file + API mock server ──
function createPreviewServer() {
  const MIME = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".xml": "application/xml",
  };

  return createServer((req, res) => {
    const url = new URL(req.url, `http://localhost:${PORT}`);

    // Build-time hydration verification: serve a completed prerender at its
    // public route while keeping normal prerender requests on the SPA shell.
    if (url.searchParams.get("__prerendered") === "1") {
      const prerenderedPath = url.pathname === "/"
        ? path.join(OUTPUT_DIR, "index.html")
        : path.join(OUTPUT_DIR, `${url.pathname.slice(1)}.html`);
      if (existsSync(prerenderedPath)) {
        res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
        res.end(readFileSync(prerenderedPath));
        return;
      }
    }

    // ── API mock: articles list ──
    if (url.pathname === "/api/content/articles") {
      const metadataPath = path.join(ARTICLES_DIR, "metadata.json");
      if (existsSync(metadataPath)) {
        const data = readFileSync(metadataPath, "utf-8");
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ success: true, articles: JSON.parse(data) }));
        return;
      }
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ success: true, articles: [] }));
      return;
    }

    // ── API mock: single article ──
    const articleMatch = url.pathname.match(/^\/api\/content\/articles\/(.+)$/);
    if (articleMatch) {
      const slug = articleMatch[1];
      const articlePath = path.join(ARTICLES_DIR, `${slug}.json`);
      if (existsSync(articlePath)) {
        const data = readFileSync(articlePath, "utf-8");
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ success: true, article: JSON.parse(data) }));
        return;
      }
      res.writeHead(404, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ success: false, error: "Article not found" }));
      return;
    }

    // ── Static file serving ──
    let filePath = path.join(DIST, url.pathname === "/" ? "index.html" : url.pathname);

    if (!existsSync(filePath)) {
      // Try adding .html extension (for clean URLs)
      const htmlPath = filePath + ".html";
      if (existsSync(htmlPath)) {
        filePath = htmlPath;
      } else {
        // Fallback to index.html for SPA routing
        filePath = path.join(DIST, "index.html");
      }
    }

    const ext = path.extname(filePath).toLowerCase();
    const contentType = MIME[ext] || "application/octet-stream";

    try {
      const content = readFileSync(filePath);
      res.writeHead(200, { "Content-Type": contentType });
      res.end(content);
    } catch {
      // Final fallback
      try {
        const fallback = readFileSync(path.join(DIST, "index.html"));
        res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
        res.end(fallback);
      } catch {
        res.writeHead(500);
        res.end("Server error");
      }
    }
  });
}

// ── Main prerender function ──
async function prerender() {
  console.log("[prerender] Starting...");
  console.log(`[prerender] cwd: ${process.cwd()}`);
  console.log(`[prerender] distDir: ${DIST}`);
  console.log(`[prerender] outputDir: ${OUTPUT_DIR}`);
  console.log(`[prerender] routes: ${ROUTES_FILE}`);

  // Read routes
  if (!existsSync(ROUTES_FILE)) {
    const message = `[prerender] Routes file not found: ${ROUTES_FILE}. Run sitemap generation first.`;
    if (STRICT) {
      throw new Error(message);
    }
    console.warn(`[prerender] WARNING: ${message}`);
    console.warn("[prerender] Using default routes (homepage only).");
    writePrerenderedFile("/", "<html><body><p>Prerender placeholder</p></body></html>");
    return;
  }

  const routes = JSON.parse(readFileSync(ROUTES_FILE, "utf-8"));
  if (!Array.isArray(routes) || routes.length === 0) {
    throw new Error(`[prerender] Routes file must contain at least one route: ${ROUTES_FILE}`);
  }
  console.log(`[prerender] Routes to render: ${routes.length}`);
  console.log(`[prerender] routes requested: ${routes.length}`);

  // Ensure output directory
  mkdirSync(OUTPUT_DIR, { recursive: true });

  // Start preview server
  const server = createPreviewServer();
  await new Promise((resolve) => server.listen(PORT, "127.0.0.1", resolve));
  console.log(`[prerender] Preview server at http://127.0.0.1:${PORT}`);

  let browser;
  try {
    browser = await launchBrowser();
  } catch (e) {
    const message = `[prerender] Browser provider failed (${e.message})`;
    await closeServer(server);
    if (STRICT) {
      throw new Error(`${message}. Strict mode requires a working browser.`);
    }
    console.warn(message);
    console.warn("[prerender] Skipping prerender — SPA fallback will serve pages.");
    return;
  }

  // Process routes in parallel with concurrency limit
  let successCount = 0;
  let failCount = 0;
  let currentIndex = 0;

  async function processRoute() {
    while (currentIndex < routes.length) {
      const idx = currentIndex++;
      const route = routes[idx];

      let page;
      try {
        page = await browser.newPage();
        page.setDefaultTimeout(TIMEOUT);

        const url = `http://127.0.0.1:${PORT}${route}`;
        console.log(`[prerender] Rendering: ${route} [${idx + 1}/${routes.length}]`);

        // Analytics and other third-party scripts can keep connections open.
        // The page-specific selector below is the reliable readiness signal.
        await page.goto(url, { waitUntil: "domcontentloaded", timeout: TIMEOUT });

        // Wait for content-specific selector
        const selector = getWaitSelector(route);
        if (selector) {
          try {
            await page.waitForSelector(selector, { timeout: TIMEOUT });
          } catch {
            throw new Error(`Required selector "${selector}" not found`);
          }
        }

        await waitForRouteMetadata(page, route);

        const html = injectStaticMetadata(await page.content(), route);
        writePrerenderedFile(route, html);

        successCount++;
        console.log(`[prerender] Rendered: ${route}`);
      } catch (err) {
        failCount++;
        console.error(`[prerender] FAILED [${idx + 1}/${routes.length}] ${route}: ${err.message}`);
      } finally {
        if (page) await page.close();
      }
    }
  }

  const workers = Array.from({ length: Math.min(CONCURRENCY, routes.length) }, () => processRoute());
  await Promise.all(workers);

  const staticRenderingPassed = successCount === routes.length && failCount === 0;
  console.log(
    `[prerender] Static rendering: ${successCount}/${routes.length} ${staticRenderingPassed ? "PASS" : "FAIL"}`,
  );

  try {
    if (STRICT && failCount === 0 && routes.includes("/") && routes.includes("/compatibility")) {
      await verifyHydration(browser);
      console.log("[prerender] Hydration: PASS");
    }
  } finally {
    await browser.close();
    await closeServer(server);
  }

  const missingOutputs = routes.filter((route) => !existsSync(getPrerenderedFilePath(route)));

  console.log("\n[prerender] Summary:");
  console.log(`[prerender] requested: ${routes.length}`);
  console.log(`[prerender] rendered: ${successCount}`);
  console.log(`[prerender] failed: ${failCount}`);
  console.log(`[prerender] output: ${OUTPUT_DIR}`);
  console.log(`[prerender] ${successCount} rendered, ${failCount} failed`);

  if (missingOutputs.length > 0) {
    console.error(`[prerender] Missing output files: ${missingOutputs.join(", ")}`);
  }

  if (
    STRICT &&
    (successCount !== routes.length || failCount !== 0 || missingOutputs.length !== 0)
  ) {
    throw new Error(
      `Strict prerender failed: requested=${routes.length}, rendered=${successCount}, failed=${failCount}, missing=${missingOutputs.length}`,
    );
  }
}

async function waitForRouteMetadata(page, route) {
  if (!route.startsWith("/relationship-patterns/") && route !== "/methodology") return;

  const canonical = `https://elemental.bond${route}`;
  const requiredSchemaTypes = route === "/methodology"
    ? ["WebPage"]
    : ["Article", "BreadcrumbList"];

  await page.waitForFunction(
    ({ expectedCanonical, schemaTypes }) => {
      const canonicals = Array.from(document.querySelectorAll('link[rel="canonical"]'));
      if (canonicals.length !== 1 || canonicals[0].href !== expectedCanonical) return false;

      const schemas = Array.from(document.querySelectorAll('script[type="application/ld+json"]'))
        .map((script) => {
          try {
            return JSON.parse(script.textContent || "{}");
          } catch {
            return null;
          }
        })
        .filter(Boolean);

      return schemaTypes.every(
        (schemaType) => schemas.filter((schema) => schema["@type"] === schemaType).length === 1,
      );
    },
    { timeout: TIMEOUT },
    { expectedCanonical: canonical, schemaTypes: requiredSchemaTypes },
  );
}

async function launchBrowser() {
  const isVercel = Boolean(process.env.VERCEL);
  console.log(`[prerender] environment: ${isVercel ? "vercel" : "local"}`);

  if (isVercel) {
    console.log("[prerender] browser provider: sparticuz");
    const [{ default: puppeteer }, { default: chromium }] = await Promise.all([
      import("puppeteer-core"),
      import("@sparticuz/chromium"),
    ]);
    const executablePath = await chromium.executablePath();
    console.log(`[prerender] executablePath: ${executablePath}`);
    const browser = await puppeteer.launch({
      args: await puppeteer.defaultArgs({ args: chromium.args, headless: "shell" }),
      executablePath,
      headless: "shell",
    });
    console.log("[prerender] browser launched");
    return browser;
  }

  console.log("[prerender] browser provider: local");
  const { default: puppeteer } = await import("puppeteer");
  const possiblePaths = getLocalBrowserPaths();
  const launchOptions = {
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-gpu"],
  };

  for (const executablePath of possiblePaths) {
    if (!existsSync(executablePath)) continue;
    try {
      console.log(`[prerender] executablePath: ${executablePath}`);
      const browser = await puppeteer.launch({ ...launchOptions, executablePath });
      console.log("[prerender] browser launched");
      return browser;
    } catch (error) {
      console.warn(`[prerender] Local browser launch failed at ${executablePath}: ${error.message}`);
    }
  }

  const executablePath = puppeteer.executablePath();
  console.log(`[prerender] executablePath: ${executablePath}`);
  const browser = await puppeteer.launch(launchOptions);
  console.log("[prerender] browser launched");
  return browser;
}

function getLocalBrowserPaths() {
  const paths = [process.env.CHROME_PATH, process.env.CHROMIUM_PATH];

  if (process.platform === "win32") {
    if (process.env.PROGRAMFILES) {
      paths.push(path.join(process.env.PROGRAMFILES, "Google", "Chrome", "Application", "chrome.exe"));
    }
    if (process.env["PROGRAMFILES(X86)"]) {
      paths.push(path.join(process.env["PROGRAMFILES(X86)"], "Google", "Chrome", "Application", "chrome.exe"));
    }
    if (process.env.LOCALAPPDATA) {
      paths.push(path.join(process.env.LOCALAPPDATA, "Google", "Chrome", "Application", "chrome.exe"));
    }
  } else if (process.platform === "darwin") {
    paths.push("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome");
  } else {
    paths.push(
      "/usr/bin/chromium",
      "/usr/bin/chromium-browser",
      "/usr/bin/google-chrome",
      "/usr/bin/google-chrome-stable",
    );
  }

  return paths.filter(Boolean);
}

function closeServer(server) {
  return new Promise((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()));
  });
}

async function verifyHydration(browser) {
  const page = await browser.newPage();
  const hydrationErrors = [];
  let activeSelector = "document";
  page.setDefaultTimeout(TIMEOUT);
  await page.setViewport(HYDRATION_VIEWPORT);
  page.on("console", (message) => {
    if (message.type() === "error" && /hydrat|mismatch/i.test(message.text())) {
      hydrationErrors.push(message.text());
    }
  });
  page.on("pageerror", (error) => {
    if (/hydrat|mismatch/i.test(error.message)) hydrationErrors.push(error.message);
  });

  try {
    const homeUrl = `http://127.0.0.1:${PORT}/?__prerendered=1`;
    console.log(`[hydration] route: /`);
    console.log(`[hydration] URL: ${homeUrl}`);
    console.log(`[hydration] viewport: ${HYDRATION_VIEWPORT.width}x${HYDRATION_VIEWPORT.height}`);
    await page.goto(homeUrl, {
      waitUntil: "domcontentloaded",
      timeout: TIMEOUT,
    });
    await page.waitForFunction(() => document.readyState === "complete", { timeout: TIMEOUT });

    activeSelector = '.bond-hero .funnel-form input[type="date"]';
    await waitForInteractiveElement(page, activeSelector);
    await setReactInputValue(page, activeSelector, "1990-01-15");
    activeSelector = ".bond-hero .funnel-form";
    await submitHydratedForm(page, activeSelector, ".funnel-result");

    const compatibilityUrl = `http://127.0.0.1:${PORT}/compatibility`;
    console.log("[hydration] route: /compatibility");
    console.log(`[hydration] URL: ${compatibilityUrl}`);
    await page.goto(compatibilityUrl, { waitUntil: "domcontentloaded", timeout: TIMEOUT });
    await page.waitForFunction(() => document.readyState === "complete", { timeout: TIMEOUT });

    activeSelector = '.compact-page > .funnel-form input[type="date"]';
    await waitForInteractiveElement(page, activeSelector);
    await setReactInputValue(page, activeSelector, "1992-04-20");
    activeSelector = ".compact-page > .funnel-form";
    await submitHydratedForm(page, activeSelector, ".paywall-grid");

    const contentRoutes = [
      "/relationship-patterns/why-do-i-keep-attracting-the-same-type-of-partner",
      "/relationship-patterns/why-do-i-always-care-more",
      "/relationship-patterns/why-does-he-pull-away-when-we-get-close",
      "/methodology",
    ];
    for (const route of contentRoutes) {
      const marker = route === "/methodology"
        ? '[data-prerender-ready="methodology"]'
        : '[data-prerender-ready="relationship-pattern-article"]';
      const contentUrl = `http://127.0.0.1:${PORT}${route}?__prerendered=1`;
      console.log(`[hydration] route: ${route}`);
      console.log(`[hydration] URL: ${contentUrl}`);
      activeSelector = marker;
      await page.goto(contentUrl, { waitUntil: "domcontentloaded", timeout: TIMEOUT });
      await page.waitForFunction(() => document.readyState === "complete", { timeout: TIMEOUT });
      await page.waitForSelector(marker, { visible: true, timeout: TIMEOUT });
    }

    if (hydrationErrors.length > 0) {
      throw new Error(`Hydration mismatch detected: ${hydrationErrors.join(" | ")}`);
    }
    console.log("[prerender] Hydration smoke test passed: funnel interactions + content page markers");
  } catch (error) {
    await logHydrationDiagnostics(page, activeSelector);
    throw error;
  } finally {
    await page.close();
  }
}

async function waitForInteractiveElement(page, selector) {
  await page.waitForSelector(selector, { visible: true, timeout: TIMEOUT });
  await page.waitForFunction(
    (targetSelector) => {
      const element = document.querySelector(targetSelector);
      if (!element) return false;
      const style = window.getComputedStyle(element);
      const rect = element.getBoundingClientRect();
      const enabled = !("disabled" in element) || !element.disabled;
      return (
        enabled &&
        style.display !== "none" &&
        style.visibility !== "hidden" &&
        Number(style.opacity) !== 0 &&
        rect.width > 0 &&
        rect.height > 0
      );
    },
    { timeout: TIMEOUT },
    selector,
  );
}

async function submitHydratedForm(page, formSelector, resultSelector) {
  await waitForInteractiveElement(page, formSelector);
  await page.$eval(formSelector, (form) => {
    form.scrollIntoView({ block: "center", inline: "center" });
    form.requestSubmit();
  });
  await page.waitForSelector(resultSelector, { visible: true, timeout: TIMEOUT });
}

async function logHydrationDiagnostics(page, selector) {
  let state;
  try {
    state = await page.evaluate((targetSelector) => {
      const element = document.querySelector(targetSelector);
      if (!element) {
        return { exists: false, visible: false, enabled: false, boundingBox: null };
      }
      const style = window.getComputedStyle(element);
      const rect = element.getBoundingClientRect();
      return {
        exists: true,
        visible:
          style.display !== "none" &&
          style.visibility !== "hidden" &&
          Number(style.opacity) !== 0 &&
          rect.width > 0 &&
          rect.height > 0,
        enabled: !("disabled" in element) || !element.disabled,
        boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height },
      };
    }, selector);
  } catch (error) {
    state = { exists: false, visible: false, enabled: false, boundingBox: null, error: error.message };
  }

  console.error(`[hydration] route: ${new URL(page.url()).pathname}`);
  console.error(`[hydration] selector: ${selector}`);
  console.error(`[hydration] exists: ${state.exists}`);
  console.error(`[hydration] visible: ${state.visible}`);
  console.error(`[hydration] enabled: ${state.enabled}`);
  console.error(`[hydration] boundingBox: ${JSON.stringify(state.boundingBox)}`);
  console.error(`[hydration] viewport: ${JSON.stringify(page.viewport())}`);
  console.error(`[hydration] currentUrl: ${page.url()}`);
  console.error(`[hydration] document.readyState: ${await page.evaluate(() => document.readyState).catch(() => "unavailable")}`);
}

async function setReactInputValue(page, selector, value) {
  await page.$eval(selector, (input, nextValue) => {
    const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set;
    setter.call(input, nextValue);
    input.dispatchEvent(new Event("input", { bubbles: true }));
    input.dispatchEvent(new Event("change", { bubbles: true }));
  }, value);
}

function escapeHtml(value) {
  return value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function injectStaticMetadata(html, route) {
  const meta = STATIC_META[route];
  if (!meta) return html;

  const canonical = `https://elemental.bond${route}`;
  const cleanHtml = html
    .replace(/<title>[\s\S]*?<\/title>/i, "")
    .replace(/<meta\s+name=["']description["'][^>]*>/gi, "")
    .replace(/<link\s+rel=["']canonical["'][^>]*>/gi, "")
    .replace(/<script\s+type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, "");

  const head = [
    `<title>${escapeHtml(meta.title)}</title>`,
    `<meta name="description" content="${escapeHtml(meta.description)}">`,
    `<link rel="canonical" href="${canonical}">`,
    `<script type="application/ld+json">${JSON.stringify(meta.schema).replaceAll("<", "\\u003c")}</script>`,
  ].join("\n    ");

  return cleanHtml.replace("</head>", `    ${head}\n  </head>`);
}

function writePrerenderedFile(route, html) {
  const filePath = getPrerenderedFilePath(route);

  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, html, "utf-8");
}

function getPrerenderedFilePath(route) {
  if (route === "/") {
    return path.join(OUTPUT_DIR, "index.html");
  } else if (route.endsWith("/")) {
    return path.join(OUTPUT_DIR, route.slice(1), "index.html");
  }
  return path.join(OUTPUT_DIR, route.slice(1) + ".html");
}

prerender().catch((err) => {
  console.error("[prerender] Fatal error:", err);
  process.exit(1);
});
